### ISSUE TITLE
Bug in 'Globio4 -doc'?

### ISSUE THREAD

**Issue by oatwood** [GLOBIO4/GlobioModelPublic#1]
Running the command 'Globio4 -doc' outputs errors for three modules - CalcSettlementDistance, CalcHumanEncroachmentMSA_V2b, and CalcInfraDisturbanceMSA.

**Comment by sebploix** [comment]
I had the same exact error. 

This come from the grass module import. 
Maybe you didn't include it. 
I needed to modify the "globio4.bat" file changing this line:

`set GRASS=C:\PBLprogs\OSGeo4W64\apps\grass\grass78`

into 
`set GRASS=C:\Program Files\GRASS GIS 8.2\` refearing to the folder where Grass is stored. 

Now it's working fine.

**Comment by oatwood** [comment]
Thanks for the tip @sebploix!
